### ISSUE TITLE
CodeCity list of running instances sometimes show false positives

### ISSUE THREAD

**Issue by SahilRS200** [google/CodeCity#414]
Hi,

i just went to the site, codecity.world, 
it listed one running instance https://google.codecity.world/

however, i saw it timing out. Suggest adding an xhr check to see if instances are having response.

**Comment by cpcallen** [comment]
Thanks for your report.

The `google.codecity.world` instance is up and running, but it is unlikely that will be accessible outside Google in the foreseeable future.  So we should do something, but health checks are not it;  instead we should add a note about this or remove it from the list of instances.

In either case, however, the issue belongs to [neilfaser/CodeCityHomepage](https://github.com/neilfraser/CodeCityHomepage/), not this repo.  Regrettably GitHub will not let me transfer the issue out-of-organisation, so I'm going to close this one and you may open one there if you wish.

**Comment by SahilRS200** [comment]
@cpcallen  thank you for your response. I hope we get to city codecity world soon
